# Generated by Django 4.0.2 on 2022-03-04 03:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_created_at_contact_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A contact with this phone number already exists'}, max_length=128, null=True, region=None),
        ),
    ]
