# Generated by Django 4.0.2 on 2022-02-28 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_date_joined_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(default=uuid.uuid1, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
